# Исключаемые директории
exclude = [
    ".git",
    ".gitignore",
	".ruff_cache",
    ".venv",
    "venv",
]

# Параметры формирования
line-length = 88
indent-width = 4

# Версия Python
target-version = "py39"

[lint]
select = ["E4", "E7", "E9", "E", "F", "I", "C90"]
ignore = []

# Допустимые/недопустимые исправления
fixable = ["ALL"]
unfixable = []


[format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = false
line-ending = "auto"