name: Build and Test

on:
  push:
    branches:
      - main
      - master
    paths:
      - src/*
      - requirements.txt
      - '*.py'
  pull_request:
    paths:
      - '!*.MD'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Code Climate before-build
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Lint with Ruff
        run: |
          ruff check .
      - run: |
          pytest --cov=. --cov-report term-missing
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Code Climate after-build
        run: |
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - uses: codeclimate/codeclimate-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECLIMATE_API_TOKEN }}
          coverage_command: pytest --cov=. --cov-report term-missing
          fail_on_error: false
